import { mkdtemp, rm } from 'fs/promises';
import os from 'os';
import path from 'path';
import { createWorkflowFile, getWorkflowsFromFiles, installIntegrationFiles } from '../src/cli/utils/n8n-files';

const run = async () => {
  const tmpDir = await mkdtemp(path.join(os.tmpdir(), 'n8n-ai-manager-'));
  process.env.N8N_FILES_PATH = tmpDir;

  const workflow = await createWorkflowFile('Smoke Test Workflow', {
    nodes: [],
    connections: {}
  });

  await installIntegrationFiles('Smoke Integration', 'Generated by smoke test.');
  const workflows = await getWorkflowsFromFiles();

  if (workflows.length === 0) {
    throw new Error('Smoke test failed: no workflows found.');
  }

  console.log(`Smoke test workflow saved at ${workflow.filePath}`);
  await rm(tmpDir, { recursive: true, force: true });
};

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
