import { mkdtemp, rm } from 'fs/promises';
import os from 'os';
import path from 'path';
import { appendLogEntry, createWorkflowFile, getWorkflowsFromFiles, installIntegrationFiles, readRecentLogs } from '../src/cli/utils/n8n-files';
import { appendDecision, getPreferenceSummary } from '../src/cli/utils/preferences';

const run = async () => {
  const tmpDir = await mkdtemp(path.join(os.tmpdir(), 'n8n-ai-manager-'));
  process.env.N8N_FILES_PATH = tmpDir;

  const workflow = await createWorkflowFile('Smoke Test Workflow', {
    nodes: [],
    connections: {}
  });

  await installIntegrationFiles('Smoke Integration', 'Generated by smoke test.');
  await appendLogEntry({
    timestamp: new Date().toISOString(),
    device: 'smoke-sensor',
    event: 'heartbeat',
    payload: { status: 'ok' }
  });
  await appendDecision({
    timestamp: new Date().toISOString(),
    actionKey: 'set-office-temp-23',
    suggestion: 'Adjust office temperature to 23C in silent mode',
    accepted: true
  });
  const workflows = await getWorkflowsFromFiles();
  const logs = await readRecentLogs(10);
  const preferences = await getPreferenceSummary();

  if (workflows.length === 0) {
    throw new Error('Smoke test failed: no workflows found.');
  }

  if (logs.length === 0) {
    throw new Error('Smoke test failed: no logs found.');
  }

  if (!preferences) {
    throw new Error('Smoke test failed: preferences summary missing.');
  }

  console.log(`Smoke test workflow saved at ${workflow.filePath}`);
  await rm(tmpDir, { recursive: true, force: true });
};

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
