export default {
    displayName: 'Custom Node',
    name: 'customNode',
    icon: 'file:custom.svg',
    group: 'input',
    version: 1,
    description: 'A custom node for n8n that integrates with AI functionalities.',
    defaults: {
        name: 'Custom Node',
        color: '#1F1F1F',
    },
    inputs: ['main'],
    outputs: ['main'],
    properties: [
        {
            displayName: 'Input',
            name: 'input',
            type: 'string',
            default: '',
            placeholder: 'Enter your input here',
            required: true,
            description: 'The input data for the custom node.',
        },
        {
            displayName: 'Output',
            name: 'output',
            type: 'string',
            default: '',
            placeholder: 'Output will be generated here',
            required: false,
            description: 'The output data generated by the custom node.',
        },
    ],
    async execute(this: IExecuteFunctions) {
        const input = this.getNodeParameter('input', 0) as string;
        // Process the input and generate output
        const output = `Processed: ${input}`;
        return this.prepareOutputData([{ json: { output } }]);
    },
};